// <auto-generated />
using System;
using GymManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219230155_SeedDataGuncelleme")]
    partial class SeedDataGuncelleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagementSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("OpenFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenSaturday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenSunday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenWednesday")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Esentepe Kampüsü",
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Name = "SAU Merkez Kampüs",
                            OpenFriday = true,
                            OpenMonday = true,
                            OpenSaturday = false,
                            OpenSunday = false,
                            OpenThursday = true,
                            OpenTuesday = true,
                            OpenWednesday = true,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mavi Durak Mevkii",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Name = "Serdivan Premium",
                            OpenFriday = true,
                            OpenMonday = true,
                            OpenSaturday = false,
                            OpenSunday = false,
                            OpenThursday = true,
                            OpenTuesday = true,
                            OpenWednesday = true,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Adapazarı Merkez",
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            Name = "Çarşı Şube",
                            OpenFriday = true,
                            OpenMonday = true,
                            OpenSaturday = false,
                            OpenSunday = false,
                            OpenThursday = true,
                            OpenTuesday = true,
                            OpenWednesday = true,
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Erenler Merkez",
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Name = "Erenler Kompleksi",
                            OpenFriday = true,
                            OpenMonday = true,
                            OpenSaturday = false,
                            OpenSunday = false,
                            OpenThursday = true,
                            OpenTuesday = true,
                            OpenWednesday = true,
                            OpeningTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Sapanca Sahil",
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Name = "Sapanca Life",
                            OpenFriday = true,
                            OpenMonday = true,
                            OpenSaturday = false,
                            OpenSunday = false,
                            OpenThursday = true,
                            OpenTuesday = true,
                            OpenWednesday = true,
                            OpeningTime = new TimeSpan(0, 7, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 60,
                            GymId = 1,
                            Name = "Fitness Standart",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 45,
                            GymId = 2,
                            Name = "Birebir Pilates",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 50,
                            GymId = 1,
                            Name = "Crossfit Seansı",
                            Price = 800m
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 90,
                            GymId = 3,
                            Name = "Kick Boks Eğitimi",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 75,
                            GymId = 2,
                            Name = "Yoga ve Meditasyon",
                            Price = 700m
                        },
                        new
                        {
                            Id = 6,
                            DurationMinutes = 60,
                            GymId = 4,
                            Name = "Yüzme Kursu",
                            Price = 900m
                        },
                        new
                        {
                            Id = 7,
                            DurationMinutes = 45,
                            GymId = 3,
                            Name = "Zumba Grup Dersi",
                            Price = 400m
                        },
                        new
                        {
                            Id = 8,
                            DurationMinutes = 30,
                            GymId = 5,
                            Name = "HIIT Antrenman",
                            Price = 600m
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 30,
                            GymId = 1,
                            Name = "Diyetisyen Danışmanlığı",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 120,
                            GymId = 5,
                            Name = "VIP Spa & Fitness",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("time");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WorkFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkSaturday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkSunday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkWednesday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GymId = 1,
                            Name = "Ahmet Yılmaz",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Specialty = "Vücut Geliştirme",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 2,
                            GymId = 2,
                            Name = "Ayşe Demir",
                            ShiftEndTime = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Specialty = "Pilates",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 3,
                            GymId = 1,
                            Name = "Mehmet Kaya",
                            ShiftEndTime = new TimeSpan(0, 22, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Specialty = "Crossfit",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 4,
                            GymId = 2,
                            Name = "Selin Yurt",
                            ShiftEndTime = new TimeSpan(0, 19, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Specialty = "Yoga",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 5,
                            GymId = 4,
                            Name = "Caner Öz",
                            ShiftEndTime = new TimeSpan(0, 16, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Specialty = "Yüzme",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 6,
                            GymId = 3,
                            Name = "Elif Ak",
                            ShiftEndTime = new TimeSpan(0, 21, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            Specialty = "Kick Boks",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 7,
                            GymId = 5,
                            Name = "Burak Arslan",
                            ShiftEndTime = new TimeSpan(0, 22, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Specialty = "Fitness",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 8,
                            GymId = 4,
                            Name = "Deniz Can",
                            ShiftEndTime = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Specialty = "Kardiyo",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 9,
                            GymId = 1,
                            Name = "Murat Yıldız",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Specialty = "Diyetisyen",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        },
                        new
                        {
                            Id = 10,
                            GymId = 3,
                            Name = "Fatma Şahin",
                            ShiftEndTime = new TimeSpan(0, 21, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 15, 0, 0, 0),
                            Specialty = "Zumba",
                            WorkFriday = true,
                            WorkMonday = true,
                            WorkSaturday = false,
                            WorkSunday = false,
                            WorkThursday = true,
                            WorkTuesday = true,
                            WorkWednesday = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "543c3933-289b-4401-831e-9279185a5382",
                            ConcurrencyStamp = "8d285034-025a-4298-82b1-8cd061f138cc",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "14686036-7975-4089-9a74-972161741544",
                            ConcurrencyStamp = "0a8447cc-ff86-4b55-a91b-f9cfabc81850",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6e522967-832d-4581-9b62-302306915f01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25f97fa9-5b6c-47f2-98b8-d808e28f378e",
                            Email = "g211210000@sakarya.edu.tr",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "G211210000@SAKARYA.EDU.TR",
                            NormalizedUserName = "G211210000@SAKARYA.EDU.TR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOyak53cDr+qFBi1BHbBg617Ak4vJf2rsbs3JGPP5MUArt9r+ixBirk+ghl1jnxgcw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4443492f-21b3-4d59-b66b-f1b1ec2ada26",
                            TwoFactorEnabled = false,
                            UserName = "g211210000@sakarya.edu.tr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6e522967-832d-4581-9b62-302306915f01",
                            RoleId = "543c3933-289b-4401-831e-9279185a5382"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymManagementSystem.Models.Appointment", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Models.Trainer", "Trainer")
                        .WithMany("Appointments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Service");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Service", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Gym", "Gym")
                        .WithMany("Services")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Gym", "Gym")
                        .WithMany("Trainers")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymManagementSystem.Models.Gym", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
